### ISSUE TITLE
individual piece moves

### ISSUE THREAD

**Issue by errorihatewindows** [errorihatewindows/Chess#18]

**Comment by errorihatewindows** [comment]
implement moveset class for every Piece, pawn needs to implement moveset and captureset individually
Moveset is virtual in Pieces, override it for every piece, Captureset needs to be overwritten only for pawn
moveset returns a list of all targets reachable by given piece on empty board, on pawn this does NOT include diagonals
captureset on pawns are diagonals (no en-passant yet dont worry ^^)

**Comment by Markus14111** [comment]
Finsihed
